[package]
name = "raft"
version = "0.0.1"
authors = ["Andrew Hobden <andrew@hoverbear.org>"]

[dependencies]
rustc-serialize = "*"
uuid = "*"
rand = "*"
log = "*"
env_logger = "*" # Important for tests.
