[package]
name = "raft"
version = "0.0.1"
authors = [ "Andrew Hobden <andrew@hoverbear.org>"
          , "James McGlashan <github@darkfox.id.au>"
	  ]
build = "build.rs"

[build-dependencies.capnpc]
git = "https://github.com/dwrensha/capnpc-rust"

[dependencies]
log = "*"
rand = "*"
uuid = "*"
bufstream = "*"
wrapped_enum = "*"

[dependencies.capnp]
git = "https://github.com/danburkert/capnproto-rust"
branch = "async"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
branch = "coalesce-events"

[dev-dependencies]
env_logger = "*"
