[package]
name = "raft"
version = "0.0.1"
authors = ["Andrew Hobden <andrew@hoverbear.org>"]
build = "build.rs"

[build-dependencies.capnpc]
git = "https://github.com/dwrensha/capnpc-rust"

[dependencies]
log = "*"
rand = "*"
uuid = "*"
bufstream = "*"
wrapped_enum = "*"

[dependencies.capnp]
git = "https://github.com/danburkert/capnproto-rust"
branch = "async"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
branch = "coalesce-events"

[dependencies.scoped_log]
git = "https://github.com/james-darkfox/rs-scoped_log"

[dev-dependencies]
env_logger = "*"
